######################################################################
# Automatically generated by qmake (2.01a) Sun Jul 10 16:19:39 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
