######################################################################
# Automatically generated by qmake (2.01a) Wed Oct 12 00:47:50 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += minimal.h
SOURCES += main.cpp minimal.cpp
