######################################################################
# Automatically generated by qmake (2.01a) Sun Jul 10 22:14:17 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
