######################################################################
# Automatically generated by qmake (2.01a) Sun Jul 10 17:09:34 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += keypress.h
SOURCES += keypress.cpp main.cpp
