######################################################################
# Automatically generated by qmake (2.01a) Wed Oct 12 00:50:15 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += proj02.h
SOURCES += main.cpp row.cpp tetris.cpp
